
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class adminAdvPanel extends javax.swing.JFrame {

    /**
     * Creates new form adminAdvPanel
     */
    public adminAdvPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adminSell_tb = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        adminRent_tb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sellingDis_bt = new javax.swing.JButton();
        deleteSell_bt = new javax.swing.JButton();
        dispRent_bt = new javax.swing.JButton();
        delRent_bt = new javax.swing.JButton();
        selligHome_txt = new javax.swing.JTextField();
        Renting_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminSell_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Price", "Rooms", "Metres", "Phone"
            }
        ));
        jScrollPane1.setViewportView(adminSell_tb);

        adminRent_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Price", "Rooms", "Metres", "Phone"
            }
        ));
        jScrollPane2.setViewportView(adminRent_tb);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("*************Selling Home***************");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("******************Renting Home***********************");

        sellingDis_bt.setText("Display Renting Home");
        sellingDis_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingDis_btActionPerformed(evt);
            }
        });

        deleteSell_bt.setText("Delete  Selling Home");
        deleteSell_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSell_btActionPerformed(evt);
            }
        });

        dispRent_bt.setText("Display Renting Home");
        dispRent_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispRent_btActionPerformed(evt);
            }
        });

        delRent_bt.setText("Delete Renting Home");
        delRent_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delRent_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(sellingDis_bt)
                                .addGap(70, 70, 70)
                                .addComponent(deleteSell_bt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addComponent(selligHome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dispRent_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delRent_bt)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Renting_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selligHome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Renting_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellingDis_bt)
                    .addComponent(deleteSell_bt)
                    .addComponent(dispRent_bt)
                    .addComponent(delRent_bt))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteSell_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSell_btActionPerformed
        DefaultTableModel  model =  (DefaultTableModel) adminSell_tb.getModel();
        ArrayList<soldHouse> user_list = userLoginPanel.soldHouse_list;
        int index = adminSell_tb.getSelectedRow();
        if(index == -1){
            if(adminSell_tb.getRowCount() == 0){
                selligHome_txt.setText("Empty");
            }
            else{
                selligHome_txt.setText("Choose user name");
            }   
        }
        else{
            user_list.remove(index-1);
            model.removeRow(index);
            
        }
    }//GEN-LAST:event_deleteSell_btActionPerformed

    private void sellingDis_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingDis_btActionPerformed
         DefaultTableModel  model =  (DefaultTableModel) adminSell_tb.getModel();
        ArrayList<soldHouse> soldHouse_list = userLoginPanel.getSoldHouse_list();
        for(int i=0;i<soldHouse_list.size();i++){
            Object[] table = {soldHouse_list.get(i).getPrice(),soldHouse_list.get(i).getNumberOfRoom(),soldHouse_list.get(i).getSquaremeters(),soldHouse_list.get(i).getConnectinPhone()};
            model.addRow(table);
        }
    }//GEN-LAST:event_sellingDis_btActionPerformed

    private void dispRent_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispRent_btActionPerformed
         DefaultTableModel  model =  (DefaultTableModel) adminRent_tb.getModel();
        ArrayList<rentHouse> RentHouse_list = userLoginPanel.getRentHouse_list();
        for(int i=0;i<RentHouse_list.size();i++){
            Object[] table = {RentHouse_list.get(i).getPrice(),RentHouse_list.get(i).getNumberOfRoom(),RentHouse_list.get(i).getSquaremeters(),RentHouse_list.get(i).getConnectinPhone()};
            model.addRow(table);
        }
    }//GEN-LAST:event_dispRent_btActionPerformed

    private void delRent_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delRent_btActionPerformed
            DefaultTableModel  model =  (DefaultTableModel) adminRent_tb.getModel();
        ArrayList<rentHouse> user_list = userLoginPanel.getRentHouse_list();
        int index = adminRent_tb.getSelectedRow();
        if(index == -1){
            if(adminRent_tb.getRowCount() == 0){
               Renting_txt.setText("Empty");
            }
            else{
                Renting_txt.setText("Choose user name");
            }   
        }
        else{
            user_list.remove(index-1);
            model.removeRow(index);
            
        }
    }//GEN-LAST:event_delRent_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminAdvPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminAdvPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminAdvPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminAdvPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminAdvPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Renting_txt;
    private javax.swing.JTable adminRent_tb;
    private javax.swing.JTable adminSell_tb;
    private javax.swing.JButton delRent_bt;
    private javax.swing.JButton deleteSell_bt;
    private javax.swing.JButton dispRent_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField selligHome_txt;
    private javax.swing.JButton sellingDis_bt;
    // End of variables declaration//GEN-END:variables
}
