
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class userLoginPanel extends javax.swing.JFrame {
    private static  ArrayList<User>user_list= new ArrayList<User>();
    public static ArrayList<rentHouse>rentHouse_list= new ArrayList<rentHouse>();
    public static ArrayList<soldHouse>soldHouse_list= new ArrayList<soldHouse>();

    public static ArrayList<rentHouse> getRentHouse_list() {
        return rentHouse_list;
    }

    public static ArrayList<soldHouse> getSoldHouse_list() {
        return soldHouse_list;
    }

    public static void setSoldHouse_list(ArrayList<soldHouse> soldHouse_list) {
        userLoginPanel.soldHouse_list = soldHouse_list;
    }

    public static void setRentHouse_list(ArrayList<rentHouse> rentHouse_list) {
        userLoginPanel.rentHouse_list = rentHouse_list;
    }

    

    public static ArrayList<User> getUser_list() {
        return user_list;
    }

    public static void setUser_list(ArrayList<User> user_list) {
        userLoginPanel.user_list = user_list;
    }
    

    /**
     * Creates new form userLogin
     */
    public userLoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLogin_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernickname_text = new javax.swing.JTextField();
        userpassword_text = new javax.swing.JPasswordField();
        userLoginOption_Panel = new javax.swing.JPanel();
        user_login = new javax.swing.JButton();
        userRegister_firstButton = new javax.swing.JButton();
        adminlogin_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("User nickname:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("User password:");

        usernickname_text.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usernickname_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernickname_textActionPerformed(evt);
            }
        });

        userpassword_text.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userpassword_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpassword_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userLogin_panelLayout = new javax.swing.GroupLayout(userLogin_panel);
        userLogin_panel.setLayout(userLogin_panelLayout);
        userLogin_panelLayout.setHorizontalGroup(
            userLogin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLogin_panelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(userLogin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(userLogin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernickname_text, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(userpassword_text))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userLogin_panelLayout.setVerticalGroup(
            userLogin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLogin_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(userLogin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernickname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(userLogin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userpassword_text, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        user_login.setText("Login");
        user_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_loginActionPerformed(evt);
            }
        });

        userRegister_firstButton.setText("Register");
        userRegister_firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRegister_firstButtonActionPerformed(evt);
            }
        });

        adminlogin_button.setText("Admin Login");
        adminlogin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminlogin_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userLoginOption_PanelLayout = new javax.swing.GroupLayout(userLoginOption_Panel);
        userLoginOption_Panel.setLayout(userLoginOption_PanelLayout);
        userLoginOption_PanelLayout.setHorizontalGroup(
            userLoginOption_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLoginOption_PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(user_login, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(userRegister_firstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(adminlogin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        userLoginOption_PanelLayout.setVerticalGroup(
            userLoginOption_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLoginOption_PanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(userLoginOption_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userRegister_firstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminlogin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userLogin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userLoginOption_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userLogin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLoginOption_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userpassword_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpassword_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userpassword_textActionPerformed

    private void usernickname_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernickname_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernickname_textActionPerformed

    private void userRegister_firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRegister_firstButtonActionPerformed
        userRegisterPanel  registerPanel = new userRegisterPanel();
        registerPanel.setVisible(true);
    }//GEN-LAST:event_userRegister_firstButtonActionPerformed

    private void user_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_loginActionPerformed
     String nickname = usernickname_text.getText();
     String password = new String(userpassword_text.getPassword());
        for(User user:user_list){
                if(user.getNick_name().equals(nickname) && user.getPassword().equals(password)){
                    JOptionPane.showMessageDialog(this,"Login successful");
                    userPanel userpanel = new userPanel();
                    userpanel.setVisible(true);
                    setVisible(true);
                    
                    
                    
                    
                }else{
                    JOptionPane.showMessageDialog(this,"Login Failed");
                }
            } 
            
        
                
            
        
    
    }//GEN-LAST:event_user_loginActionPerformed

    private void adminlogin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminlogin_buttonActionPerformed
         adminLoginPanel loginPanel = new adminLoginPanel();
         loginPanel.setVisible(true);
       
    }//GEN-LAST:event_adminlogin_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userLoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userLoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userLoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userLoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userLoginPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminlogin_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel userLoginOption_Panel;
    private javax.swing.JPanel userLogin_panel;
    private javax.swing.JButton userRegister_firstButton;
    private javax.swing.JButton user_login;
    private javax.swing.JTextField usernickname_text;
    private javax.swing.JPasswordField userpassword_text;
    // End of variables declaration//GEN-END:variables
}
